services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=librarydb'
      - 'MYSQL_ROOT_PASSWORD=!@i57qrjbb7rXK'  # Add this line
    ports:
      - '3306:3306'